### PR TITLE
chore: add pyupgrade pre-commit hook

### PR DESCRIPTION
**Pull request by MindTooth**
I've been following https://github.com/asottile on Twitch the past few days.  He is the author of `pre-commit`.  He also has a tool called https://github.com/asottile/pyupgrade which makes sure that the syntax follows the latest changes to Python.

The hook is now set to always upgrade to Python 3.8 and above syntax.

Please look at the changes and perhaps test it locally.

### CODE REVIEW

**Comment by tomrtk** [comment]
Looks good to me, but it has introduced some 3.10 constructs in the code.

**Comment by MindTooth** [comment]
> Looks good to me, but it has introduced some 3.10 constructs in the code.

Care to point to them?  Maybe I need to tweak the tool a bit.

Also, did find it strange that `pre-commit.ci` did changes that the job doesn't mention. 🤔

**Comment by tomrtk** [comment]
[This](https://github.com/MindTooth/fish-code/pull/103/files#diff-3242de2a57605a844d12bce70704553e409b0ebf6a14497b7a822545e1535d23L255) new way to define a [union](https://docs.python.org/3.10/whatsnew/3.10.html#pep-604-new-type-union-operator) is an example.

It probably ok, but something to keep in mind.

**Comment by MindTooth** [comment]
But `from __future__ import annotations` solves it on older versions right?  As long as it's imported why should be fine right.

**Review by tomrtk — APPROVED** [review]

**Pull request merged**
