### PR TITLE
fix: enable paused jobs to be restarted

### PR DESCRIPTION
**Pull request by tomrtk**
- enable paused jobs(if a job is processing when `nina`is stopped, it is paused) to be restarted from `ui`.
- handle exceptions during job processing to gracefully log errors, such as in issue #44.

### CODE REVIEW

**Review by MindTooth — APPROVED** [review]

**Comment by R0flcopt3r** [comment]
Am I missing something, or should I have a button to start the job? The attached image shows a job that was running, then SIGTERM-ing nina, and starting it again. To be absolutely sure this isn't some cache related issue I reopened in private browsing.

image

I reinstalled deps and nina itself after switching  to this branch.

**Comment by tomrtk** [comment]
> Am I missing something, or should I have a button to start the job? 

It should show as paused when you restart `nina`

**Comment by R0flcopt3r** [comment]
> > Am I missing something, or should I have a button to start the job?
> 
> It should show as paused when you restart `nina`

That is not happening for me.. It seems to be exiting cleanly:

```
INFO:core.services:Batch 11 out of 450 completed in 2.77s, job 3% complete
^C
INFO:     Shutting down
INFO:uvicorn.error:Shutting down
INFO:     Shutting down
INFO:uvicorn.error:Shutting down
INFO:     Waiting for application shutdown.
INFO:uvicorn.error:Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:uvicorn.error:Application shutdown complete.
INFO:     Finished server process [11750]
INFO:uvicorn.error:Finished server process [11750]
INFO:     Waiting for application shutdown.
INFO:uvicorn.error:Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:uvicorn.error:Application shutdown complete.
INFO:     Finished server process [11749]
INFO:uvicorn.error:Finished server process [11749]
INFO:core.services:Stopping
INFO:     127.0.0.1:36826 - "POST /predictions/fishy/ HTTP/1.1" 200 OK
INFO:     Shutting down
INFO:uvicorn.error:Shutting down
INFO:     Waiting for application shutdown.
INFO:uvicorn.error:Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:uvicorn.error:Application shutdown complete.
INFO:     Finished server process [11751]
INFO:uvicorn.error:Finished server process [11751]
INFO:core.services:Batch 12 out of 450 completed in 2.74s, job 3% complete
INFO:core.services:Scheduler ending.
INFO:core.services:Stopped
```

**Comment by MindTooth** [comment]
Well, the pause button is AFAIK, “disabled” because we did not have said functionality.  I have a faint memory I did some stuff to it.

**Comment by tomrtk** [comment]
> Well, the pause button is AFAIK, “disabled” because we did not have said functionality. I have a faint memory I did some stuff to it.

From a users point of view it has not been an feature, but the logic in a job processing has been putting jobs to paused if the program it shutdown. 

So this patch only let you start them again, by being able to toggle the button if it the job status is paused, which has not been possible before.

**Comment by R0flcopt3r** [comment]
As mentioned on discord, there are some race condition things causing the job to not always get paused. On my computer, it almost never happens...

**Comment by MindTooth** [comment]
Ready to be merged for now, and we tackle the other stuff later?

**Comment by tomrtk** [comment]
I have now done a little more on handling of errors and jobs not being put to paused during shutdown and if a non-graceful shutdown occurs. 
There is also now an `error` status if the job occurs a `RuntimeError` during processing. Eg. #44 will now get an error status. So far it is the only indication in `ui`, to get more info it still need to look at the logs, but handling an error message from `core` to `ui` should be handled in a separate patch.

I am considering this done for now, if you could have a look if it is ok to merge.

**Comment by tomrtk** [comment]
Also `pyupgrade` did some type hinting syntax changes to `service.py` after I added `from __future__ import annotations` to the file.

**Review by MindTooth — APPROVED** [review]
I’m okay with pyupgrade changes.

**Pull request merged**
