### PR TITLE
Move to new datatables.net-dt module syntax

### PR DESCRIPTION
**Pull request by MindTooth**
Seems like the way of installing it has changes since we last begynt to use the library.

I want to move it into its own file like jsTree.  But that's for another time. 😄

### CODE REVIEW

**Comment by tomrtk** [comment]
I believe we do not have a good test for checking the object table, so it may need to be tested manually.

**Comment by MindTooth** [comment]
I thought it worked, but seems I had cache laying around. 😢

**Comment by MindTooth** [comment]
I find it strange that we did not use it for the "Video" tab too. 😅 

Screenshot 2023-08-17 at 19 29 18

**Comment by MindTooth** [comment]
I'll tackle jsTree next.  Been having a few issues.

**Review by tomrtk — APPROVED** [review]

**Pull request merged**
