### PR TITLE
ci: add windows

### PR DESCRIPTION
**Pull request by MindTooth**

### CODE REVIEW

**Comment by MindTooth** [comment]
Opening `abbor.png` somehow is impossible.  Tried installing FFmpeg, but did not do the trick.  Then I tried OpenCV, but the action was not for Windows.

Not sure how important this is.  But it's not good if something breaks when NINA runs the application.

**Comment by R0flcopt3r** [comment]
> Opening `abbor.png` somehow is impossible. Tried installing FFmpeg, but did not do the trick. Then I tried OpenCV, but the action was not for Windows.
> 
> Not sure how important this is. But it's not good if something breaks when NINA runs the application.

I'm booting my vm and I'll try to run the test suite there.

**Comment by R0flcopt3r** [comment]
@MindTooth #78 should solve the abbor loading issue.

**Comment by MindTooth** [comment]
> @MindTooth #78 should solve the abbor loading issue.

Push them here to test?

**Comment by R0flcopt3r** [comment]
> > @MindTooth #78 should solve the abbor loading issue.
> 
> Push them here to test?

I rebased on this, and changed the target branch here as well. Dependabot wants to update a bunch of stuff though?

**Comment by R0flcopt3r** [comment]
> > > @MindTooth #78 should solve the abbor loading issue.
> > 
> > 
> > Push them here to test?
> 
> I rebased on this, and changed the target branch here as well. Dependabot wants to update a bunch of stuff though?

scratch that, I just pushed the changes from PR #78 into this.

**Review by R0flcopt3r — APPROVED** [review]

**Pull request merged**
