### PR TITLE
build: added `cpu` and `gpu` extra requirement

### PR DESCRIPTION
**Pull request by tomrtk**
added `cpu` and `gpu` extra requirement in setup.cfg to make install of torch
with CUDA easier.

To install package:
`pip install <url-to-whl>[cpu]`
or
`pip install <url-to-whl>[gpu] --find-links https://download.pytorch.org/whl/torch_stable.html`

Ref #96.

### CODE REVIEW

**Review by MindTooth — APPROVED** [review]

**Review by Kad1n — APPROVED** [review]

**Comment by R0flcopt3r** [comment]
Should properly update the readme with this before merging.

**Comment by R0flcopt3r** [comment]
Testing this on windows with:
```
(.venv) PS C:\Users\eirik\Git\fish-code> pip install -e '.[gpu,testing,dev]'
```

results in this error:

```
ERROR: Could not find a version that satisfies the requirement torchvision==0.10.0+cu111; extra == "gpu" (from nina[dev,gpu,testing]) (from versions: 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.2, 0.2.2.post2, 0.2.2.post3, 0.9.0, 0.9.1, 0.10.0)
ERROR: No matching distribution found for torchvision==0.10.0+cu111; extra == "gpu"
```

This also seems to happen with torchvision if I strip `+cu111` from torchvision. I am rushing this comment slightly to make sure you don't merge with two approves. I'll test a little bit more and try and find a solution that works.

---

cpu works as expected.

**Comment by MindTooth** [comment]
Upgraded `pip`?

**Comment by R0flcopt3r** [comment]
> 
> 
> Upgraded `pip`?

yes,
```
(.venv) PS C:\Users\eirik\Git\fish-code> C:\Users\eirik\Git\fish-code\.venv\Scripts\python.exe -m pip install --upgrade pip
Requirement already satisfied: pip in c:\users\eirik\git\fish-code\.venv\lib\site-packages (21.1.3)
```

**Comment by R0flcopt3r** [comment]
I suggest we do this to get easy windows compatability. 

``` patch
From f969d88a423bfdd8fb9e1673e555b61a47af892b Mon Sep 17 00:00:00 2001
From: R0flcopt3r <12752060+R0flcopt3r@users.noreply.github.com>
Date: Mon, 19 Jul 2021 11:44:08 +0200
Subject: [PATCH] windows cuda

---
 setup.cfg | 3 +++
 1 file changed, 3 insertions(+)

diff --git a/setup.cfg b/setup.cfg
index b0d6f90..5faf983 100644
--- a/setup.cfg
+++ b/setup.cfg
@@ -78,6 +78,9 @@ dev =
 gpu =
     torch==1.9.0+cu111
     torchvision==0.10.0+cu111
+win-gpu =
+    torch@https://download.pytorch.org/whl/cu111/torch-1.9.0%%2Bcu111-cp39-cp39-win_amd64.whl
+    torchvision@https://download.pytorch.org/whl/cu111/torchvision-0.10.0%%2Bcu111-cp39-cp39-win_amd64.whl
 testing =
     coverage[toml]
     pytest>=4.0.0
--
2.30.2.windows.1
```

Only problem here is we have to specify which python version, and for the links below it is set to python 3.9, as that is what my windows vm runs. Perhaps add `win-gpu{3.9,3.8}` with their respective links..?

I tried to find some alternative to pip's `--find-links`, but it seems depricated with setuptools(?) and I don't really know where to look, and I have other things I need to get to.

This will also make the gpu switch redundant, as if I recall correctly torch handles linux properly, and cuda is supported by default.

**Comment by R0flcopt3r** [comment]
> This will also make the gpu switch redundant, as if I recall correctly torch handles linux properly, and cuda is supported by default.

Just confirmed this on linux:
```
pip install -e '.[testing,dev,cpu]'
pip install ipython
.venv/bin/ipython
Python 3.9.6 (default, Jun 29 2021, 00:00:00)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.25.0 -- An enhanced Interactive Python. Type '?' for help.
In [1]: import torch

In [2]: torch.cuda.is_available()
Out[2]: True
```

**Comment by tomrtk** [comment]
> Testing this on windows with:
> 
> ```
> (.venv) PS C:\Users\eirik\Git\fish-code> pip install -e '.[gpu,testing,dev]'
> ```
> 
> results in this error:
> 
> ```
> ERROR: Could not find a version that satisfies the requirement torchvision==0.10.0+cu111; extra == "gpu" (from nina[dev,gpu,testing]) (from versions: 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.2, 0.2.2.post2, 0.2.2.post3, 0.9.0, 0.9.1, 0.10.0)
> ERROR: No matching distribution found for torchvision==0.10.0+cu111; extra == "gpu"
> ```
> 
> This also seems to happen with torchvision if I strip `+cu111` from torchvision. I am rushing this comment slightly to make sure you don't merge with two approves. I'll test a little bit more and try and find a solution that works.
> 
> cpu works as expected.

As described in PR if installing with gpu target you need to supply link to pip.

**Comment by tomrtk** [comment]
> Should properly update the readme with this before merging.

I was passing that on to whoever finalize #96

**Comment by tomrtk** [comment]
> I suggest we do this to get easy windows compatability.
> 
> ```diff
> From f969d88a423bfdd8fb9e1673e555b61a47af892b Mon Sep 17 00:00:00 2001
> From: R0flcopt3r <12752060+R0flcopt3r@users.noreply.github.com>
> Date: Mon, 19 Jul 2021 11:44:08 +0200
> Subject: [PATCH] windows cuda
> 
> ---
>  setup.cfg | 3 +++
>  1 file changed, 3 insertions(+)
> 
> diff --git a/setup.cfg b/setup.cfg
> index b0d6f90..5faf983 100644
> --- a/setup.cfg
> +++ b/setup.cfg
> @@ -78,6 +78,9 @@ dev =
>  gpu =
>      torch==1.9.0+cu111
>      torchvision==0.10.0+cu111
> +win-gpu =
> +    torch@https://download.pytorch.org/whl/cu111/torch-1.9.0%%2Bcu111-cp39-cp39-win_amd64.whl
> +    torchvision@https://download.pytorch.org/whl/cu111/torchvision-0.10.0%%2Bcu111-cp39-cp39-win_amd64.whl
>  testing =
>      coverage[toml]
>      pytest>=4.0.0
> --
> 2.30.2.windows.1
> ```
> 
> Only problem here is we have to specify which python version, and for the links below it is set to python 3.9, as that is what my windows vm runs. Perhaps add `win-gpu{3.9,3.8}` with their respective links..?
> 
> I tried to find some alternative to pip's `--find-links`, but it seems depricated with setuptools(?) and I don't really know where to look, and I have other things I need to get to.
> 
> This will also make the gpu switch redundant, as if I recall correctly torch handles linux properly, and cuda is supported by default.

I would rather not go down this route as this will result in many extra targets. I would rater the user documentation for installing with gpu supply link to pip command, as in PR message.

**Comment by R0flcopt3r** [comment]
> > Testing this on windows with:
> > ```
> > (.venv) PS C:\Users\eirik\Git\fish-code> pip install -e '.[gpu,testing,dev]'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > results in this error:
> > ```
> > ERROR: Could not find a version that satisfies the requirement torchvision==0.10.0+cu111; extra == "gpu" (from nina[dev,gpu,testing]) (from versions: 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.2, 0.2.2.post2, 0.2.2.post3, 0.9.0, 0.9.1, 0.10.0)
> > ERROR: No matching distribution found for torchvision==0.10.0+cu111; extra == "gpu"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This also seems to happen with torchvision if I strip `+cu111` from torchvision. I am rushing this comment slightly to make sure you don't merge with two approves. I'll test a little bit more and try and find a solution that works.
> > cpu works as expected.
> 
> As described in PR if installing with gpu target you need to supply link to pip.

I completely missed that part..

**Pull request merged**
