### PR TITLE
Add TailwindCSS plugin for Prettier & ESLint

### PR DESCRIPTION
**Pull request by MindTooth**
https://github.com/prettier/prettier/issues/15025

Prettier 3.0 introduced a new plugin system.  This does not currently work with pre-commit.  Hence, I removed the hook entirely.

### CODE REVIEW

**Comment by MindTooth** [comment]
I also added ESLint. 🤦🏻‍♂️ 

With the jQuery rules set, I get the following errors:
```

/Users/birgerjn/Developer/fish-code/src/ui/src/js/jstree.js
   7:10  error  Identifier 'attach_jstree' is not in camel case                        camelcase
  12:11  error  'calculatedUrl' is not defined                                         no-undef
  20:18  error  'calculatedUrl' is not defined                                         no-undef
  27:15  error  'tree' is not defined                                                  no-undef
  29:31  error  Expected '===' and instead saw '=='                                    eqeqeq
  30:17  error  'tree' is not defined                                                  no-undef
  31:17  error  'tree' is not defined                                                  no-undef
  66:11  error  Identifier 'selected_videos' is not in camel case                      camelcase
  69:11  error  Identifier 'selected_videos' is not in camel case                      camelcase
  72:7   error  Identifier 'selected_videos' is not in camel case                      camelcase
  72:7   error  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  78:10  error  Identifier 'attach_jstree' is not in camel case                        camelcase

/Users/birgerjn/Developer/fish-code/src/ui/src/js/projects.js
   21:28  error  Read-only global 'jQuery' should not be modified                              no-global-assign
   23:10  error  Identifier 'attach_jstree' is not in camel case                               camelcase
   38:36  error  Identifier 'object_id' is not in camel case                                   camelcase
   45:36  error  Identifier 'object_id' is not in camel case                                   camelcase
   57:39  error  Identifier 'object_id' is not in camel case                                   camelcase
   60:19  error  Identifier 'object_id' is not in camel case                                   camelcase
   62:31  error  Identifier 'object_id' is not in camel case                                   camelcase
   83:3   error  'tree' is not defined                                                         no-undef
   88:3   error  'btn' is not defined                                                          no-undef
   90:7   error  'btn' is not defined                                                          no-undef
   90:38  error  'btn' is not defined                                                          no-undef
   91:5   error  'btn' is not defined                                                          no-undef
   98:11  error  'btn' is not defined                                                          no-undef
   99:11  error  'btn' is not defined                                                          no-undef
  100:11  error  'btn' is not defined                                                          no-undef
  102:31  error  'textStatus' is defined but never used. Allowed unused args must match /^_/u  no-unused-vars
  118:7   error  Identifier 'table_template' is not in camel case                              camelcase
  130:27  error  'data' is defined but never used. Allowed unused args must match /^_/u        no-unused-vars
  130:33  error  'type' is defined but never used. Allowed unused args must match /^_/u        no-unused-vars
  130:39  error  'row' is defined but never used. Allowed unused args must match /^_/u         no-unused-vars
  140:33  error  'type' is defined but never used. Allowed unused args must match /^_/u        no-unused-vars
  140:39  error  'row' is defined but never used. Allowed unused args must match /^_/u         no-unused-vars
  152:27  error  'data' is defined but never used. Allowed unused args must match /^_/u        no-unused-vars
  152:33  error  'type' is defined but never used. Allowed unused args must match /^_/u        no-unused-vars
  152:44  error  'meta' is defined but never used. Allowed unused args must match /^_/u        no-unused-vars
  170:34  error  'index' is defined but never used. Allowed unused args must match /^_/u       no-unused-vars
  170:41  error  'tableLoop' is defined but never used. Allowed unused args must match /^_/u   no-unused-vars
  170:52  error  'rowLoop' is defined but never used. Allowed unused args must match /^_/u     no-unused-vars

✖ 40 problems (40 errors, 0 warnings)
```

I look into fixing this.

**Review by tomrtk — APPROVED** [review]
Should we add bulk style change commits to a `.git-blame-ignore-revs` file?

**Comment by MindTooth** [comment]
> Should we add bulk style change commits to a `.git-blame-ignore-revs` file?

How does that combine with us using squash?  A good idea for sure.  Never been using it.

**Comment by tomrtk** [comment]
> > Should we add bulk style change commits to a `.git-blame-ignore-revs` file?
> 
> How does that combine with us using squash? A good idea for sure. Never been using it.

In cases like this, I think the cleanup should be done locally, one commit changing formatter and one commit applying the changes from the formatter, then rebase merge.

**Pull request merged**
