### PR TITLE
refactor(ui): new icons for filebrowser

### LINKED ISSUE #136: Fix icons in the file browser
The current file browser is not pretty to look at.  There is no real difference between files, folders, or different types of files.

Step to fix this:
- Add more icons for jsTree to use
- Trim down the mime types to only be groups

### LINKED ISSUE #140: File browser throws errors when opening folder without correct premissions
Selecting a folder without sufficient read premissions results in a ASGI stacktrace error message in the terminal. The API still works after the crash, but this should be handled more neatly in `get_directory_listing()` or `get_storage_path()`.

In order to reproduce, launch the application and navigate to the UI in the file browser. Create a project, then open the job creation window in the new project. Try to expand any folder with insufficient read permissions, for example `/root` on Linux systems. (Unless you are the root user) This should show the following stacktrace in the terminal.

```
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "/home/kad/Projects/Git/code/.venv/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 398, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/kad/Projects/Git/code/.venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/kad/Projects/Git/code/.venv/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/home/kad/Projects/Git/code/.venv/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/kad/Projects/Git/code/.venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/kad/Projects/Git/code/.venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/kad/Projects/Git/code/.venv/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/kad/Projects/Git/code/.venv/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/kad/Projects/Git/code/.venv/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/home/kad/Projects/Git/code/.venv/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/home/kad/Projects/Git/code/.venv/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/home/kad/Projects/Git/code/.venv/lib/python3.8/site-packages/fastapi/routing.py", line 216, in app
    raw_response = await run_endpoint_function(
  File "/home/kad/Projects/Git/code/.venv/lib/python3.8/site-packages/fastapi/routing.py", line 149, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/kad/Projects/Git/code/src/core/api/api.py", line 665, in get_storage_path
    return get_directory_listing(decrypted_path)
  File "/home/kad/Projects/Git/code/src/core/services.py", line 613, in get_directory_listing
    for p in normalized_path.iterdir():
  File "/usr/lib64/python3.8/pathlib.py", line 1122, in iterdir
    for name in self._accessor.listdir(self):
PermissionError: [Errno 13] Permission denied: '/root'
```

### PR DESCRIPTION
**Pull request by MindTooth**
I've now reworked the icons a bit.  Still a bit off based on the fact that we use the default theme.  The checkboxes are a bit off.

The steps I've done is:
* Bundled [Bootstrap](https://icons.getbootstrap.com/) icons
* Tweaked `postcss-url` to make it more automatic.  **Note!** Still too static as it can't copy the non-CSS files.
* Tweaked the types plugin of jsTree
* Open all root nodes when ready
* Implement permission error in both `core` and `ui`
* Use callback for jsTree loading data from the endpoint

I'm beginning to lean towards utilizing a bundler tool like Webpack, Snowpack, or something to make the bundling more streamlined.  I feel it begins to be a bit hackish.

Closes #136, closes #140.

---

Current demo:

Screen Shot 2021-07-28 at 14 30 03

### CODE REVIEW

**Review by Kad1n — APPROVED** [review]

**Comment by MindTooth** [comment]
I've added support for handling permission problems.  This closes #140.

Screen Shot 2021-07-29 at 15 27 16

**Comment by MindTooth** [comment]
I feel that we should also hide hidden files by default.  End up with too much cruft.

**Review by tomrtk — APPROVED** [review]

**Comment by MindTooth** [comment]
I don't think my way of testing for `PermissionError` is ideal.  Now it writes files to the temp folder and sets them to be unreadable, and it then seems that then `pytest` is unable to delete them afterward.  At least locally I'm getting `rm` errors.

I attempted at solving the issue with something like this:
```diff
diff --git a/tests/unit/core/integration/test_api.py b/tests/unit/core/integration/test_api.py
index b1a7dce..6e8e76d 100644
--- a/tests/unit/core/integration/test_api.py
+++ b/tests/unit/core/integration/test_api.py
@@ -50,7 +50,9 @@ def empty_directory(tmp_path_factory) -> str:
     d = tmp_path_factory.mktemp("empty")
     chmod(d, 0o000)
 
-    return str(d)
+    yield str(d)
+
+    chmod(d, 0o755)
```

I also looked at mocking the exception, but I'm beginning to thread in deep waters.

---

Also, `setuptools_scm` does not really work when downloading a tar.  I've tried setting `fallback_version` from reading the docs but doesn't seem to help any. 🤔  I'm having major issues trying to then test it on Windows where I use the tar for this branch.  Currently, I've not tested this on Windows.  And I really must.

**Comment by tomrtk** [comment]
> I don't think my way of testing for `PermissionError` is ideal. Now it writes files to the temp folder and sets them to be unreadable, and it then seems that then `pytest` is unable to delete them afterward. At least locally I'm getting `rm` errors.
> 
> I attempted at solving the issue with something like this:
> 
> ```diff
> diff --git a/tests/unit/core/integration/test_api.py b/tests/unit/core/integration/test_api.py
> index b1a7dce..6e8e76d 100644
> --- a/tests/unit/core/integration/test_api.py
> +++ b/tests/unit/core/integration/test_api.py
> @@ -50,7 +50,9 @@ def empty_directory(mock, tmp_path_factory) -> str:
>      d = tmp_path_factory.mktemp("empty")
>      chmod(d, 0o000)
>  
> -    return str(d)
> +    yield str(d)
> +
> +    chmod(d, 0o755)
> ```
> 
> I also looked at mocking the exception, but I'm beginning to thread in deep waters.
> 
> Also, `setuptools_scm` does not really work when downloading a tar. I've tried setting `fallback_version` from reading the docs but doesn't seem to help any. thinking I'm having major issues trying to then test it on Windows where I use the tar for this branch. Currently, I've not tested this on Windows. And I really must.

To mock a `PermissionError` in a unit test of `get_directory_listing` it looks you could do:

```python
#  tests/unit/core/unit/test_service.py
@patch("os.access", return_value=False)
def test_get_directory_listing_permission_error(tmp_path) -> None:
    """Test if directory is not accessible."""
    error_dir = tmp_path / "test"
    error_dir.mkdir()

    with pytest.raises(PermissionError):
        _ = get_directory_listing(str(error_dir))
```
similar in test of api:
```python
# tests/unit/core/integration/test_api.py
@pytest.fixture
def empty_directory_encoded_normal_perm(tmp_path: Path) -> str:
    """Encode the empty directory."""
    path_encoded = base64.urlsafe_b64encode(str(tmp_path).encode())

    return str(path_encoded, "utf-8")

@patch("os.access", return_value=False)
def test_get_storage_permissionerror(mock, empty_directory_encoded_normal_perm):
    """Test getting storage with PermissionError."""

    with TestClient(api.core_api) as client:

        response = client.get(
            f"storage/{empty_directory_encoded_normal_perm}",
        )
        assert response.status_code == 403

**Review by tomrtk — APPROVED** [review]

**Pull request merged**
